### ISSUE TITLE
Fail to import citation of publication from YAML

### ISSUE THREAD

**Issue by pkiraly** [LibreCat/LibreCat#163]
I freshly installed Librecat from scratch. It installed the dev branch. When I indexed the devel/publication.yml, then I received back the stored values I found a big difference.

```yml
...
citation:
  ama: Matamoros MA, Saiz A, Peñuelas M, et al. Function of glutathione peroxidases
    in legume root nodules. <em>Journal of Experimental Botany</em>. 2015;66(10):2979–2990.
  apa: Matamoros, M. A., Saiz, A., Peñuelas, M., Bustos-Sanmamed, P., Mulet, J. M.,
    Barja, M. V., Rouhier, N., et al. (2015). Function of glutathione peroxidases
    in legume root nodules. <em>Journal of Experimental Botany</em>, <em>66</em>(10),
    2979–2990.
...
```
then the retrieval with command
```
bin/librecat publication get 2737383
```
returns
```yml
citation:
  american-medical-association: 0
  apa: 0
  chicago-fullnote-bibliography: 0
  ieee: 0
  modern-language-association: 0
```
It seems the citations are not imported at all. Is it a bug, or I have to install something else (I haven't installed the CSL tool)? Is it no longer to import citations from the YAML?
