### ISSUE TITLE
Check publication_status unpublished

### ISSUE THREAD

**Issue by christianmahnke** [LibreCat/LibreCat#244]
Error
```
3145388
ERROR: not a valid publication
/publication_status: Not in enum list: draft, submitted, accepted, inpress, epub_ahead, published.
```
Record
```
 ---
_id: 3145388
_version: 1
citation:
  ama: 'Décultot E, Adler H, eds. Johann Georg Sulzer. Kurzer Begriff aller Wissenschaften : erste (1745) und zweite (1759) Auflage. Basel: Schwabe'
  apa: 'Décultot, E., & Adler, H. (Eds.). (n.d.). Johann Georg Sulzer. Kurzer Begriff aller Wissenschaften : erste (1745) und zweite (1759) Auflage. Basel: Schwabe.'
  chicago: 'Décultot, Elisabeth, and Hans Adler, eds. Johann Georg Sulzer. Kurzer Begriff Aller Wissenschaften : Erste (1745) Und Zweite (1759) Auflage. Basel: Schwabe, n.d.'
  ieee: 'E. Décultot and H. Adler, Eds., Johann Georg Sulzer. Kurzer Begriff aller Wissenschaften : erste (1745) und zweite (1759) Auflage. Basel: Schwabe.'
  mla: 'Décultot, Elisabeth, and Hans Adler, eds. Johann Georg Sulzer. Kurzer Begriff Aller Wissenschaften : Erste (1745) Und Zweite (1759) Auflage. Basel: Schwabe. Print.'
  short: 'E. Décultot, H. Adler, eds., Johann Georg Sulzer. Kurzer Begriff Aller Wissenschaften : Erste (1745) Und Zweite (1759) Auflage, Schwabe, Basel, n.d.'
creator:
  id: 102
  login: witt_gro
date_created: 2017-03-22T15:11:17Z
date_updated: 2017-03-22T15:11:17Z
editor:
  - first_name: Elisabeth
    full_name: 'Décultot, Elisabeth'
    last_name: Décultot
  - first_name: Hans
    full_name: 'Adler, Hans'
    last_name: Adler
language:
  - iso: ger
message: aufklärung
page: 'LXXXIII, 243'
place: Basel
publication_identifier:
  isbn:
    - 978-3-7965-3217-7
publication_status: unpublished
publisher: Schwabe
status: public
title: 'Johann Georg Sulzer. Kurzer Begriff aller Wissenschaften : erste (1745) und zweite (1759) Auflage'
type: book_editor
user_id: 102
year: 2014
```

Maybe this is introduced by the BibTex import? That's the only place were I found a possible cause.
