### ISSUE TITLE
CLI import problem 

### ISSUE THREAD

**Issue by njahn82** [LibreCat/LibreCat#270]
I am stuck when trying to import crossref records from the command line.

When trying:

```
bin/librecat publication fetch crossref 10.1007/978-1-4419-9569-8 > tmp_cr.yaml
bin/librecat publication add tmp_cr.yaml
```
I get the following error message:

```
Not a HASH reference at /srv/LibreCat/lib/LibreCat/Cmd/publication.pm line 287, <GEN0> line 51.
```

**Comment by njahn82** [comment]
Seems that the resulting yaml is the problem, because all metadata is now a block of the `content_domain` tag.

```
---
- content-domain:
    crossmark-restriction: !!perl/scalar:JSON::PP::Boolean 0
    domain: []
  created:
    date-parts:
    - - 5
      - 26
    date-time: 2011-05-26T19:17:16Z
    timestamp: 1306437436000
  doi: 10.1007/978-1-4419-9569-8
  editor:
  - first_name: Heinz H.
    last_name: Bauschke
  - first_name: Regina S.
    last_name: Burachik
  - first_name: Patrick L.
    last_name: Combettes
  - first_name: Veit
    last_name: Elser
  - first_name: D. Russell
    last_name: Luke
  - first_name: Henry
    last_name: Wolkowicz
  is-referenced-by-count: 19
  issn-type:
  - type: print
    value: 1931-6828
  original-title: []
  place: New York, NY
  publication_identifier:
    isbn:
    - 978-1-4419-9568-1
    - 978-1-4419-9569-8
    issn:
    - 1931-6828
  publication_status: published
  published-print:
    date-parts:
    - - 2011
  publisher: Springer New York
  reference-count: 0
  references-count: 0
  relation: {}
  short-container-title: []
  short-title: []
  status: new
  title: Fixed-Point Algorithms for Inverse Problems in Science and Engineering
  type: book_editor
  year: 2011
...
```
