### ISSUE TITLE
Publications with only open access main_file_links not being recognized as open access  

### ISSUE THREAD

**Issue by ThriceGood** [LibreCat/LibreCat#418]
I have publications with only main_file_links and no file uploaded locally. Open_access=1 in these publications but they are not being recognized as open access in  the interface. the 'Open Access Publications' link says 0.

**Comment by vpeil** [comment]
Branch https://github.com/LibreCat/LibreCat/compare/pr/issue_418_2nd_edition contains some progress on this issue.

The changes were quite smooth. The only problem remains is the open access filter with the correct number.

Changing the default facets for open_access into
```
open_access:
  terms:
    fields: ['file.open_access', 'main_file_link.open_access']
    size: 1
```
gives on the first a look a correct result. But it seems to count a record with OA file **and** OA link twice.
Any thoughts here?
