### ISSUE TITLE
No Arrays in Configs! No Arrays in Configs!

### ISSUE THREAD

**Issue by petrakohorst** [LibreCat/LibreCat#461]
We have stumbled upon a (small) problem with arrays in configs - if layers are used.

Since configs are merged into one hash across layers, any array that is present both in the core and a layer (or in two different layers) will be overwritten, instead of merged.

Two major examples where this is currently the case:

- hooks.yml: if two layers define publication-update.before_fixes , the config in one layer will overwrite the other one.
- catmandu.yml / helper_plugins: defining a helper plugin in one layer will overwrite the configured helper plugin in a second layer.

So far none of these are critical.
But still my suggestion is: write all configs as hashes. (No Arrays in Configs! ;-))

hooks.yml example: Instead of
```
hooks:
  publication-publish:
    before_fixes:
      - orcid_push
```

Use
```
hooks:
  publication-publish:
    before_fixes:
      orcid_push: 1
```

I know that the data structure itself doesn't make sense, but it would solve the issue and all hooks would be combined instead of overwritten.
Same for the helper plugins. And any other item that is currently a list/array in the config files.

What do you think? Would this be possible?
