### ISSUE TITLE
Missing "bin/librecat researcher [cmd] ..." command?

### ISSUE THREAD

**Issue by pkiraly** [LibreCat/LibreCat#72]
Hi I tried to add researchers the validated way (similar than publications) with the following command:

```
bin/librecat researcher add data/researchers.yml
```

I received:

```
Unrecognized command: researcher.

Usage:
        commands: list the application's commands
            help: display a command's help screen

          config: export the librecat config
         convert: convert objects with catmandu
            copy: manage librecat metadata store - copy to another store
           count: manage librecat metadata store - count number of objects
          delete: manage librecat metadata store - delete objects
      department: manage librecat departments
            drop: manage librecat metadata store - drop objects
          export: manage librecat metadata store - export objects
      file_store: manage librecat file stores
        generate: generate various files
          import: manage librecat metadata stores - import objects
           index: manage index jobs
         project: manage librecat projects
     publication: manage librecat publications
           queue: show job queue status
  research_group: manage librecat research_group-s
         schemas: manage librecat schemas
         sitemap: generate siteindex and sitemaps
            user: manage librecat users
          worker: manage librecat worker processes
```

The strange thing that there are command for department, project, publication and research_group, but no command for researcher and award.
