### ISSUE TITLE
cannot clear first multi-field input

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#723]
When using multi-fields (e.g. "authors"), I can delete all inputs, except the first one,
which is fine, but the first one should be cleared when the button "-" is hit.

**Comment by nicolasfranck** [comment]
When this happens: 

* open edit-page
* choose a new value from the dropdown list
* the input becomes gray. The button "-" does not do anything anymore.

**Comment by petrakohorst** [comment]
Cannot recreate this problem. Current dev branch, generated forms...

All multi-fields (department, project, author etc.) can be filled and deleted/emptied as you would expect. That means, all inputs except the first one are removed when clicking the "-". The first input field is not removed but cleared and the readonly property is removed.

**Comment by nicolasfranck** [comment]
ah right. It didn't explain this very well: it only happens when the field attribute "multiple" is set to 0.
For example:
```
publication_types:
  image:
    fields:
      basic_fields:
        department:
          mandatory: 1
          multiple: 0
```
