### ISSUE TITLE
user whitelisting not consistent

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#748]
The way whitelisting of users is done in librecat is not consistent: it makes promises that it cannot fulfil.

In the configuration you can have

```
user:
  sources:
    - store: store1
      bag: bag1
      username_attr: login
    - store: store2
      bag: bag2
      username_attr: orcid
```

This way you can:

* match "login" with attribute "login" from bag1
* match "login" with attribute "orcid" from bag2

That's all fine,
but is does not force you to look in the main user database.
The user that is returned by methods LibreCat::Model::User::find_by_username
and LibreCat::Model::User::get is not necessarily contained in the
internal user database.

Proposal:
  * deprecate current use of configuration option "user.sources":
  * force "store" to "search" or "main". Default is "main".
  * force "bag" to "user", meaning you ignore the configuration option

Problems:
  * what to do with the store "builtin_users"?

**Comment by vpeil** [comment]
I understand the store builtin_users as for testing or development. This can be done differently, though. I can't imagine someone uses it in production

**Comment by nics** [comment]
We use it in production to store the superuser

**Comment by nics** [comment]
But @nicolasfranck is right, the feature is problematic, not one of my best ideas ;-)

**Comment by phochste** [comment]
@nicolasfranck what is the relation of this ticket to https://github.com/LibreCat/LibreCat/pull/747 ? Does this PR close this issue , is it unrelated to this issue , or something else?

**Comment by nicolasfranck** [comment]
@phochste issue #747 is about blocking the user that was selected. This is about how we should select a user.

**Comment by nicolasfranck** [comment]
The method `get` and `add` of this model are also contradicting each other: while `add` updates data in the underlying bag and search_bag, the `get` retrieves data from the first bag in a list.

For example, put this in `config/catmandu.local.yml` .. 

```
user:
  sources:
    - store: builtin_users
      username_attr: login
    - store: search
      bag: user
      username_attr: login
```

..and you will strange behaviour:

* user "einstein" (id 1234) appears in the list of users in `/librecat/admin/account`
* if you try to update that record using the form, the changes will appear in `/librecat/admin/account`, but if you return to the form nothing of the like will be visible.
* reason: the form uses `user->get` to retrieve, which should be correct, were it not that the `get` is overwritten in `LibreCat::Model::User`..
