### ISSUE TITLE
use of hooks?

### ISSUE THREAD

**Issue by nicolasfranck** [LibreCat/LibreCat#931]
The way the hooks are used now are not always ideal:

e.g. if I configure a list of `after_fixes` in `publication-update`,
then these hooks will ALWAYS run, no matter the outcome of
the validation. And one cannot change that behaviour because
they are destined to run AFTER that even, according to the documentation.

e.g.

```
hooks:
  # Code that runs when updating a publication
  publication-update:
    after_fixes:
      - audit_message
      - sleep
```

Meaning, these hooks will run, even when no update was saved due to validation errors:
* the hook `audit_message`, which registers an update
* the hook `sleep` will run, which sleeps for a second

Of course, one can come up with other names like `after_error_fixes` and `after_success_fixes`,
but those will only apply to this kind of event.

Wouldn't it be more simple to do it like this:

```
hook:
  "publication-update-before":
    - hook1
  "publication-update-failed":
   - hook2
  "publication-update-success":
   - hook3
  "publication-update-after:"
   - hook4
```

That would make it more extendable. Each event can then choose as many subevents
as it wants.
